### ISSUE TITLE
Error "no interface 'JSX.IntrinsicElements' exists." occurs in vscode

### ISSUE THREAD

**Issue by cdoremus** [XDean/deno-create-react-app#1]
After I create an app using deno-create-react-app and I open vscode, all the TSX files show this error in the JSX section:
"JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists."

This error does not occur in Aleph.

**Comment by XDean** [comment]
Sorry @cdoremus. I'm using IDEA. It works well. 

![image](https://user-images.githubusercontent.com/12760952/112701509-cdf7b380-8ecb-11eb-9b08-6f64e7184929.png)

Can you confirm if the `tsconfig.json` affect? There is `"noImplicitAny": false,` in it.
